In [ ]:
import numpy as np
import pandas as pd
ar1 = np.array([100, 200, np.nan, 300])
ser1= pd.Series(ar1)

In [ ]:
ar1.mean(), ser1.mean()

(np.float64(nan), np.float64(200.0))

In [ ]:
data = np.arange(15,30).reshape(5,3)
dfx = pd.DataFrame(data, index=['apple', 'banana', 'kiwi', 'grapes', 'mango'],
                   columns =['store1','store2', 'store3'])
dfx

store1  store2  store3
apple       15      16      17
banana      18      19      20
kiwi        21      22      23
grapes      24      25      26
mango       27      28      29

In [ ]:
dfx['store4'] = np.nan
dfx.loc['watermelon']= np.arange(15,19)
dfx.loc['oranges']=np.nan
dfx['store5']=np.nan
dfx['store4']['apple']=20.
dfx

<ipython-input-7-5c811b51d48b>:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  dfx['store4']['apple']=20.


store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     NaN
banana        18.0    19.0    20.0     NaN     NaN
kiwi          21.0    22.0    23.0     NaN     NaN
grapes        24.0    25.0    26.0     NaN     NaN
mango         27.0    28.0    29.0     NaN     NaN
watermelon    15.0    16.0    17.0    18.0     NaN
oranges        NaN     NaN     NaN     NaN     NaN

In [ ]:
#Let's compute the total quantity of fruits  sold
ser2 = dfx.store4
ser2.sum()

np.float64(38.0)

In [ ]:
ser2.mean()

np.float64(19.0)

In [ ]:
ser2.cumsum()

apple         20.0
banana         NaN
kiwi           NaN
grapes         NaN
mango          NaN
watermelon    38.0
oranges        NaN
Name: store4, dtype: float64

In [ ]:
filleDf=dfx.fillna(0)
filleDf

store1  store2  store3  store4  store5
apple         15.0    16.0    17.0    20.0     0.0
banana        18.0    19.0    20.0     0.0     0.0
kiwi          21.0    22.0    23.0     0.0     0.0
grapes        24.0    25.0    26.0     0.0     0.0
mango         27.0    28.0    29.0     0.0     0.0
watermelon    15.0    16.0    17.0    18.0     0.0
oranges        0.0     0.0     0.0     0.0     0.0

In [ ]:
dfx.mean()

store1    20.0
store2    21.0
store3    22.0
store4    19.0
store5     NaN
dtype: float64

In [ ]:
filleDf.mean()

store1    17.142857
store2    18.000000
store3    18.857143
store4     5.428571
store5     0.000000
dtype: float64

Metode backward (nilai)

In [14]:
dfx.store4.fillna(method='ffill')

<ipython-input-14-d45b080c1221>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.store4.fillna(method='ffill')


apple         20.0
banana        20.0
kiwi          20.0
grapes        20.0
mango         20.0
watermelon    18.0
oranges       18.0
Name: store4, dtype: float64

In [15]:
dfx.store4.fillna(method='bfill')

<ipython-input-15-2e7395bf265b>:1: FutureWarning: Series.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  dfx.store4.fillna(method='bfill')


apple         20.0
banana        18.0
kiwi          18.0
grapes        18.0
mango         18.0
watermelon    18.0
oranges        NaN
Name: store4, dtype: float64

Metode Interpolasi

In [16]:
ser3=pd.Series([100,np.nan,np.nan,np.nan,292])
ser3.interpolate()

0    100.0
1    148.0
2    196.0
3    244.0
4    292.0
dtype: float64

Mengubah Index

In [17]:
import numpy as np
data=np.arange(15).reshape((3,5))
indexers=['Rainfall', 'Humidity', 'Wind']
dframe1=pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])
dframe1

Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [18]:
dframe1.index=dframe1.index.map(str.upper)
dframe1

Bergen  Oslo  Trondheim  Stavanger  Kristiansand
RAINFALL       0     1          2          3             4
HUMIDITY       5     6          7          8             9
WIND          10    11         12         13            14

In [19]:
dframe1.index=dframe1.index.map(str.lower)
dframe1

Bergen  Oslo  Trondheim  Stavanger  Kristiansand
rainfall       0     1          2          3             4
humidity       5     6          7          8             9
wind          10    11         12         13            14

In [20]:
dframe1.rename(index=str.title, columns=str.lower)

bergen  oslo  trondheim  stavanger  kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [22]:
dframe1.rename(index=str.title, columns=str.upper)

BERGEN  OSLO  TRONDHEIM  STAVANGER  KRISTIANSAND
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

Indented Block

In [23]:
#Let's say we have data on the heights of a group of students as for

In [24]:
height=[120,122,125,127,121,123,137,131,161,145,141,132]
height

[120, 122, 125, 127, 121, 123, 137, 131, 161, 145, 141, 132]

In [25]:
bins =[118, 125, 135, 160, 200]
category = pd.cut(height, bins)
category

[(118, 125], (118, 125], (118, 125], (125, 135], (118, 125], ..., (125, 135], (160, 200], (135, 160], (135, 160], (125, 135]]
Length: 12
Categories (4, interval[int64, right]): [(118, 125] < (125, 135] < (135, 160] < (160, 200]]

In [26]:
category2=pd.cut(height, [118, 126, 136, 161, 200], right=False)
category2

[[118, 126), [118, 126), [118, 126), [126, 136), [118, 126), ..., [126, 136), [161, 200), [136, 161), [136, 161), [126, 136)]
Length: 12
Categories (4, interval[int64, left]): [[118, 126) < [126, 136) < [136, 161) < [161, 200)]

Arti kurung yang berbeda, angka dikurung awal nilai tidak dimasukkan berbeda dengan angka setelah kurung siku , nilai dimasukkan.

Arti Kurung dalam Interval

(118, 125] :

( berarti nilai 118 tidak termasuk dalam interval.
] berarti nilai 125 termasuk dalam interval.
Jadi, interval ini mencakup semua nilai dari 118 (eksklusif) hingga 125 (inklusif).
Secara umum:

( berarti eksklusif (nilai tidak termasuk).
] berarti inklusif (nilai termasuk).

In [27]:
pd.value_counts(category)

<ipython-input-27-7a767266afe9>:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(category)


(118, 125]    5
(125, 135]    3
(135, 160]    3
(160, 200]    1
Name: count, dtype: int64

In [28]:
#MENAMBAH LABEL
bin_names=['Short Height', 'Average height', 'Good Height', 'Taller']
pd.cut(height, bins, labels=bin_names)

['Short Height', 'Short Height', 'Short Height', 'Average height', 'Short Height', ..., 'Average height', 'Taller', 'Good Height', 'Good Height', 'Average height']
Length: 12
Categories (4, object): ['Short Height' < 'Average height' < 'Good Height' < 'Taller']

In [31]:
#Data Outliers
import pandas as pd
df=pd.read_csv('https://raw.githubusercontent.com/PacktPublishing/hands-on-exploratory-data-analysis-with-python/master/Chapter%204/sales.csv?authuser=0')
df.head(10)

Account           Company  Order                SKU        Country  Year  \
0  123456779         Kulas Inc  99985   s9-supercomputer          Aruba  1981   
1  123456784            GitHub  99986   s4-supercomputer         Brazil  2001   
2  123456782         Kulas Inc  99990  s10-supercomputer     Montserrat  1973   
3  123456783         My SQ Man  99999   s1-supercomputer    El Salvador  2015   
4  123456787         ABC Dogma  99996   s6-supercomputer         Poland  1970   
5  123456778  Super Sexy Dingo  99996   s9-supercomputer     Costa Rica  2004   
6  123456783         ABC Dogma  99981  s11-supercomputer          Spain  2006   
7  123456785         ABC Dogma  99998   s9-supercomputer        Belarus  2015   
8  123456778         Loolo INC  99997   s8-supercomputer      Mauritius  1999   
9  123456775         Kulas Inc  99997   s7-supercomputer  French Guiana  2004   

   Quantity  UnitPrice  transactionComplete  
0      5148        545                False  
1      3262        383                False  
2      9119        407                 True  
3      3097        615                False  
4      3356         91                 True  
5      2474        136                 True  
6      4081        195                False  
7      6576        603                False  
8      2460         36                False  
9      1831        664                 True

In [34]:
df['TotalPrice']=df['UnitPrice']*df['Quantity']
df.head(10)

Account           Company  Order                SKU        Country  Year  \
0  123456779         Kulas Inc  99985   s9-supercomputer          Aruba  1981   
1  123456784            GitHub  99986   s4-supercomputer         Brazil  2001   
2  123456782         Kulas Inc  99990  s10-supercomputer     Montserrat  1973   
3  123456783         My SQ Man  99999   s1-supercomputer    El Salvador  2015   
4  123456787         ABC Dogma  99996   s6-supercomputer         Poland  1970   
5  123456778  Super Sexy Dingo  99996   s9-supercomputer     Costa Rica  2004   
6  123456783         ABC Dogma  99981  s11-supercomputer          Spain  2006   
7  123456785         ABC Dogma  99998   s9-supercomputer        Belarus  2015   
8  123456778         Loolo INC  99997   s8-supercomputer      Mauritius  1999   
9  123456775         Kulas Inc  99997   s7-supercomputer  French Guiana  2004   

   Quantity  UnitPrice  transactionComplete  TotalPrice  
0      5148        545                False     2805660  
1      3262        383                False     1249346  
2      9119        407                 True     3711433  
3      3097        615                False     1904655  
4      3356         91                 True      305396  
5      2474        136                 True      336464  
6      4081        195                False      795795  
7      6576        603                False     3965328  
8      2460         36                False       88560  
9      1831        664                 True     1215784

In [35]:
TotalTransaction=df['TotalPrice']
TotalTransaction[np.abs(TotalTransaction) >3000000]

2       3711433
7       3965328
13      4758900
15      5189372
17      3989325
         ...   
9977    3475824
9984    5251134
9987    5670420
9991    5735513
9996    3018490
Name: TotalPrice, Length: 2094, dtype: int64

In [36]:
df[np.abs(TotalTransaction)> 654]

Account           Company  Order                SKU  \
0     123456779         Kulas Inc  99985   s9-supercomputer   
1     123456784            GitHub  99986   s4-supercomputer   
2     123456782         Kulas Inc  99990  s10-supercomputer   
3     123456783         My SQ Man  99999   s1-supercomputer   
4     123456787         ABC Dogma  99996   s6-supercomputer   
...         ...               ...    ...                ...   
9995  123456784       Pryianka Ji  99987   s1-supercomputer   
9996  123456775          Will LLC  99985   s3-supercomputer   
9997  123456774         Kulas Inc  99982   s2-supercomputer   
9998  123456781         Loolo INC  99986   s5-supercomputer   
9999  123456775  Super Sexy Dingo  99987   s1-supercomputer   

                       Country  Year  Quantity  UnitPrice  \
0                        Aruba  1981      5148        545   
1                       Brazil  2001      3262        383   
2                   Montserrat  1973      9119        407   
3                  El Salvador  2015      3097        615   
4                       Poland  1970      3356         91   
...                        ...   ...       ...        ...   
9995                   Jamaica  1983       886        475   
9996                   Vietnam  2002      9995        302   
9997  Northern Mariana Islands  1979      1421        249   
9998                      Mali  1991      2342        506   
9999                Luxembourg  1982      5282        222   

      transactionComplete  TotalPrice  
0                   False     2805660  
1                   False     1249346  
2                    True     3711433  
3                   False     1904655  
4                    True      305396  
...                   ...         ...  
9995                False      420850  
9996                 True     3018490  
9997                 True      353829  
9998                False     1185052  
9999                False     1172604  

[9997 rows x 10 columns]

**CHALLENGE**

In [67]:
data=pd.read_csv('https://cdn.uisi.ac.id/covid_2020-12-01.csv')
data.head(16)

provinsi  lokasi_lintang  lokasi_bujur  jumlah_kasus  \
0                         ACEH        4.225615     96.910522          8301   
1                         BALI       -8.369472    115.131714         13988   
2                       BANTEN       -6.456736    106.109004         13215   
3                     BENGKULU       -3.533584    102.338421          1842   
4   DAERAH ISTIMEWA YOGYAKARTA       -7.894502    110.444878          6073   
5                  DKI JAKARTA       -6.204699    106.836118        137919   
6                    GORONTALO        0.687003    122.376058          3110   
7                        JAMBI       -1.697698    102.723640          1993   
8                   JAWA BARAT       -6.920432    107.603708         53395   
9                  JAWA TENGAH       -7.259097    110.201115         56626   
10                  JAWA TIMUR       -7.723346    112.732941         62313   
11            KALIMANTAN BARAT       -0.086475    111.121178          2438   
12          KALIMANTAN SELATAN       -2.993595    115.438578         13281   
13           KALIMANTAN TENGAH       -1.602485    113.417654          6122   
14            KALIMANTAN TIMUR        0.453858    116.468440         19748   
15            KALIMANTAN UTARA        2.891013    116.218879          1523   

    jumlah_sembuh  jumlah_meninggal  jumlah_dirawat  laki_laki  perempuan  \
0            6631               329            1341       4052       4231   
1           12466               428            1094       7218       6765   
2            8830               334            4051       6470       6730   
3            1427                77             338        778        986   
4            4471               147            1455       2762       3308   
5          125008              2683           10228      69088      66593   
6            2970                90              50       1528       1580   
7            1384                37             572        665        603   
8           44509               922            7964      26912      25410   
9           40369              2368           13889      17346      19436   
10          54863              4438            3012      30024      32118   
11           2055                22             361       1331       1094   
12          11794               532             955       6839       6241   
13           4681               194            1247       3101       2928   
14          16384               561            2803      11691       7665   
15            995                18             510        932        591   

    usia_0_5  usia_6_18  usia_19_30  usia_31_45  usia_46_59  usia_60_keatas  
0        180        444        1927        2938        1967             827  
1        276        869        3569        3818        3541            1831  
2        331       1234        3065        4097        3315            1080  
3         35        152         410         613         399             213  
4        182        849        1477        1358        1315             636  
5       3600       9931       33950       40993       29429           14283  
6         56        159        1113        1065         522             153  
7         56        281         491         596         364             154  
8       1785       6487       12655       15456       11107            4381  
9       1656       5497       11761       15187       14735            7569  
10      1012       4306       12338       17354       17795            8818  
11        59        195         597         709         586             242  
12       385       1234        3273        4000        2980            1074  
13       193        641        1606        1879        1331             403  
14       415       1349        4702        6172        3807            1269  
15        29        122         447         529         302              90

In [68]:
#Menampilkan jumlah baris dan kolom
data.shape

(34, 15)

In [69]:
#Menambah kolom baru dengan singkatan nan
data['SES']=np.nan
data.head(16)

provinsi  lokasi_lintang  lokasi_bujur  jumlah_kasus  \
0                         ACEH        4.225615     96.910522          8301   
1                         BALI       -8.369472    115.131714         13988   
2                       BANTEN       -6.456736    106.109004         13215   
3                     BENGKULU       -3.533584    102.338421          1842   
4   DAERAH ISTIMEWA YOGYAKARTA       -7.894502    110.444878          6073   
5                  DKI JAKARTA       -6.204699    106.836118        137919   
6                    GORONTALO        0.687003    122.376058          3110   
7                        JAMBI       -1.697698    102.723640          1993   
8                   JAWA BARAT       -6.920432    107.603708         53395   
9                  JAWA TENGAH       -7.259097    110.201115         56626   
10                  JAWA TIMUR       -7.723346    112.732941         62313   
11            KALIMANTAN BARAT       -0.086475    111.121178          2438   
12          KALIMANTAN SELATAN       -2.993595    115.438578         13281   
13           KALIMANTAN TENGAH       -1.602485    113.417654          6122   
14            KALIMANTAN TIMUR        0.453858    116.468440         19748   
15            KALIMANTAN UTARA        2.891013    116.218879          1523   

    jumlah_sembuh  jumlah_meninggal  jumlah_dirawat  laki_laki  perempuan  \
0            6631               329            1341       4052       4231   
1           12466               428            1094       7218       6765   
2            8830               334            4051       6470       6730   
3            1427                77             338        778        986   
4            4471               147            1455       2762       3308   
5          125008              2683           10228      69088      66593   
6            2970                90              50       1528       1580   
7            1384                37             572        665        603   
8           44509               922            7964      26912      25410   
9           40369              2368           13889      17346      19436   
10          54863              4438            3012      30024      32118   
11           2055                22             361       1331       1094   
12          11794               532             955       6839       6241   
13           4681               194            1247       3101       2928   
14          16384               561            2803      11691       7665   
15            995                18             510        932        591   

    usia_0_5  usia_6_18  usia_19_30  usia_31_45  usia_46_59  usia_60_keatas  \
0        180        444        1927        2938        1967             827   
1        276        869        3569        3818        3541            1831   
2        331       1234        3065        4097        3315            1080   
3         35        152         410         613         399             213   
4        182        849        1477        1358        1315             636   
5       3600       9931       33950       40993       29429           14283   
6         56        159        1113        1065         522             153   
7         56        281         491         596         364             154   
8       1785       6487       12655       15456       11107            4381   
9       1656       5497       11761       15187       14735            7569   
10      1012       4306       12338       17354       17795            8818   
11        59        195         597         709         586             242   
12       385       1234        3273        4000        2980            1074   
13       193        641        1606        1879        1331             403   
14       415       1349        4702        6172        3807            1269   
15        29        122         447         529         302              90   

    SES  
0   NaN  
1   NaN  
2   NaN  
3

In [70]:
#Mengubah NAN dengan string 'Kosong
data['SES']= data['SES'].fillna(0)
data.head(16)

provinsi  lokasi_lintang  lokasi_bujur  jumlah_kasus  \
0                         ACEH        4.225615     96.910522          8301   
1                         BALI       -8.369472    115.131714         13988   
2                       BANTEN       -6.456736    106.109004         13215   
3                     BENGKULU       -3.533584    102.338421          1842   
4   DAERAH ISTIMEWA YOGYAKARTA       -7.894502    110.444878          6073   
5                  DKI JAKARTA       -6.204699    106.836118        137919   
6                    GORONTALO        0.687003    122.376058          3110   
7                        JAMBI       -1.697698    102.723640          1993   
8                   JAWA BARAT       -6.920432    107.603708         53395   
9                  JAWA TENGAH       -7.259097    110.201115         56626   
10                  JAWA TIMUR       -7.723346    112.732941         62313   
11            KALIMANTAN BARAT       -0.086475    111.121178          2438   
12          KALIMANTAN SELATAN       -2.993595    115.438578         13281   
13           KALIMANTAN TENGAH       -1.602485    113.417654          6122   
14            KALIMANTAN TIMUR        0.453858    116.468440         19748   
15            KALIMANTAN UTARA        2.891013    116.218879          1523   

    jumlah_sembuh  jumlah_meninggal  jumlah_dirawat  laki_laki  perempuan  \
0            6631               329            1341       4052       4231   
1           12466               428            1094       7218       6765   
2            8830               334            4051       6470       6730   
3            1427                77             338        778        986   
4            4471               147            1455       2762       3308   
5          125008              2683           10228      69088      66593   
6            2970                90              50       1528       1580   
7            1384                37             572        665        603   
8           44509               922            7964      26912      25410   
9           40369              2368           13889      17346      19436   
10          54863              4438            3012      30024      32118   
11           2055                22             361       1331       1094   
12          11794               532             955       6839       6241   
13           4681               194            1247       3101       2928   
14          16384               561            2803      11691       7665   
15            995                18             510        932        591   

    usia_0_5  usia_6_18  usia_19_30  usia_31_45  usia_46_59  usia_60_keatas  \
0        180        444        1927        2938        1967             827   
1        276        869        3569        3818        3541            1831   
2        331       1234        3065        4097        3315            1080   
3         35        152         410         613         399             213   
4        182        849        1477        1358        1315             636   
5       3600       9931       33950       40993       29429           14283   
6         56        159        1113        1065         522             153   
7         56        281         491         596         364             154   
8       1785       6487       12655       15456       11107            4381   
9       1656       5497       11761       15187       14735            7569   
10      1012       4306       12338       17354       17795            8818   
11        59        195         597         709         586             242   
12       385       1234        3273        4000        2980            1074   
13       193        641        1606        1879        1331             403   
14       415       1349        4702        6172        3807            1269   
15        29        122         447         529         302              90   

    SES  
0   0.0  
1   0.0  
2   0.0  
3

In [71]:
#Menampilkan kolom jumlah kasus diatas 300
jumlahKasus=data["jumlah_kasus"]
jumlahKasus[np.abs(jumlahKasus) > 300]

0       8301
1      13988
2      13215
3       1842
4       6073
5     137919
6       3110
7       1993
8      53395
9      56626
10     62313
11      2438
12     13281
13      6122
14     19748
15      1523
16      1036
17      5490
18      3939
19      4620
20      2376
21      4697
22      1242
23     10094
24      5352
25     20238
26      1473
27     20804
28      1872
29      6594
30      6962
31     20098
32      9530
33     15671
Name: jumlah_kasus, dtype: int64

In [77]:
#Menampilkan jumlah kasus untuk usia 0-5 tahun untuk provinsi dengan kasus lebih dari 30
jumlahKasus = data["jumlah_kasus"]
data[jumlahKasus>300][["provinsi", "usia_0_5", "jumlah_kasus"]]


provinsi  usia_0_5  jumlah_kasus
0                         ACEH       180          8301
1                         BALI       276         13988
2                       BANTEN       331         13215
3                     BENGKULU        35          1842
4   DAERAH ISTIMEWA YOGYAKARTA       182          6073
5                  DKI JAKARTA      3600        137919
6                    GORONTALO        56          3110
7                        JAMBI        56          1993
8                   JAWA BARAT      1785         53395
9                  JAWA TENGAH      1656         56626
10                  JAWA TIMUR      1012         62313
11            KALIMANTAN BARAT        59          2438
12          KALIMANTAN SELATAN       385         13281
13           KALIMANTAN TENGAH       193          6122
14            KALIMANTAN TIMUR       415         19748
15            KALIMANTAN UTARA        29          1523
16   KEPULAUAN BANGKA BELITUNG        35          1036
17              KEPULAUAN RIAU       165          5490
18                     LAMPUNG        90          3939
19                      MALUKU        65          4620
20                MALUKU UTARA        37          2376
21         NUSA TENGGARA BARAT       120          4697
22         NUSA TENGGARA TIMUR        21          1242
23                       PAPUA       250         10094
24                 PAPUA BARAT       168          5352
25                        RIAU       712         20238
26              SULAWESI BARAT        18          1473
27            SULAWESI SELATAN       470         20804
28             SULAWESI TENGAH        29          1872
29           SULAWESI TENGGARA        98          6594
30              SULAWESI UTARA       120          6962
31              SUMATERA BARAT       556         20098
32            SUMATERA SELATAN       347          9530
33              SUMATERA UTARA       284         15671